### ISSUE TITLE
Chaining signal from psygnal to Qt Signals

### ISSUE THREAD

**Issue by Czaki** [tlambert03/psygnal#47]
When trying to propagate event from psygnal to Qt Signal (to use Qt benefit of invoking in proper thread for example) now you need to declare additional functions to do this. It will be nice to have code such this working:

```python
import sys

from qtpy.QtCore import Signal, QObject, QCoreApplication
from psygnal import Signal as PSignal

class SomePythonClass:
    some_inner_signal = PSignal(str)

    def call_signal(self):
        self.some_inner_signal.emit("test text")

class SampleQtClass(QObject):
    sample_signal = Signal()

    def __init__(self):
        super().__init__()
        self._inner_object = SomePythonClass()
        self._inner_object.some_inner_signal.connect(self.sample_signal.emit)

    def call_func(self):
        self._inner_object.call_signal()


def called():
    print("text")

if __name__ == '__main__':
    app = QCoreApplication(sys.argv)

    ob = SampleQtClass()
    ob.sample_signal.connect(called)

    ob.call_func()
```

At this moment I do not know option to inspect Qt Signal signature, but maybe good workaround will be add `maxargs` argument to `connect` function to allow user provide this information in code?

**Comment by tlambert03** [comment]
interesting...

> At this moment I do not know option to inspect Qt Signal signature

just dug into this a bit.  _if_ we had a pointer to `ob` (the instance of `SampleQtClass`), then you can get good information like this:

```py
class SampleQtClass(QObject):
    sample_signal = Signal(int)

ob = SampleQtClass()
meta_obj = ob.metaObject()
for i in range(meta_obj.methodCount()):
    meta_meth = meta_obj.method(i)
    if meta_meth.name().contains(b'sample_signal'):
        n_params = meta_meth.parameterCount()
        break
```

however, from the perspective of psygnal `connect`, if all we have is `ob.sample_signal.emit`, then the best I've been able to do is get the `SignalInstance` (i.e. `ob.sample_signal`), with `ob.sample_signal.emit.__self__`.

But that's where I ran cold, since I can't for the life of me figure out how to get back to the object `ob`, or the Signal `SampleQtClass.sample_signal` given just the SignalInstance.

**Comment by Czaki** [comment]
I check PyQt5 code (from pypi tar.gz file) and it is stored in the `bound_pyobject` class variable of `qpycore_pyqtBoundSignal` and I do not find any place where is exported to python API.

**Comment by tlambert03** [comment]
PyQt5 is actually much easier... since the `signal_instance` has an attribute `.signal` that holds the string signature:

`ob.sample_signal.signal`

------

here's a ridiculous approach that does appear to work for both pyside2 and pyqt5:

```py
def get_signal_signature(sig_instance: SignalInstance) -> str:
    # pyqt holds the signature string in the `.signal` attribute
    sgnl = getattr(sig_instance, "signal", None)
    if isinstance(sgnl, str):
        return sgnl

    # pyside2 doesn't... 
    # we have to call it with ridiculous params to get the err
    try:
        sig_instance.emit(*(1,) * 50)
    except TypeError as e:
        if "only accepts" in str(e):
            return str(e).split("only accepts")[0].strip()
    return None


def n_sig_instance_params(sig_instance: SignalInstance):
    sig = get_signal_signature(sig_instance)
    if not (sig and "(" in sig):
        return None
    inner = sig.split("(", 1)[1].split(")", 1)[0]
    return inner.count(",") + 1 if inner else 0
```

**Comment by Czaki** [comment]
hm. Nice idea. I do not think about parsing the string, but it looks like a nice approach.

Did you think it is a nice final solution or maybe a better option is to ask on the PyQt5 mail list to add more verbose information in python API? (I do not know where to place such request for PySide).

**Comment by tlambert03** [comment]
> I do not know where to place such request for PySide

yeah, I didn't know either.  I created an SO post here: https://stackoverflow.com/questions/69976089/get-signature-of-a-bound-signalinstance-in-pyside2

we'll see if it gets any bites.  For PyQt I think we're all set... 

> Did you think it is a nice final solution 

I think it could work... it would be nice to be a bit more confident that the `try: sig_instance.emit(*(1,) * 50)` is never going to actually emit a signal.  can you think of any edge cases where that might actually _not_ raise an error?

one last possibility is that we don't parse and split the string signature for arguments, but rather just look at the Type error itself?
On PyQt it looks like this:
```
TypeError: MyObj.some_sig[int] signal has 1 argument(s) but 50 provided
```
on PySide it looks like this:
```
TypeError: some_sig(int) only accepts 1 argument(s), 50 given!
```

so we could try to just directly grab the `1` there instead of parsing `some_sig(int)`. thoughts?

**Comment by Czaki** [comment]
> so we could try to just directly grab the `1` there instead of parsing `some_sig(int)`. thoughts?

I'm worried about a side effects of such an approach. 
In such a case, I would first try to go through stacktrace and try to get the object from the calling connect frame.
But this assumes that stack exists (there are some stackless  python implementation - maybe not wort to think)

**Comment by tlambert03** [comment]
> I'm worried about a side effects of such an approach.

not following.  do you mean the side effects of calling `.emit(ridiclous_args)` in the first place?  or side effects of grabbing the `1` from the error message, instead of counting the parameters in the signature (which is also just a string printed in the error message).

I think stack inspection sounds a lot more error prone than just parsing the error string

**Comment by Czaki** [comment]
> I think stack inspection sounds a lot more error prone than just parsing the error string

and what happens if there is no error?

**Comment by tlambert03** [comment]
> and what happens if there is no error?

then we're basically out of luck on PySide.  that's why I was asking above "can you think of any edge cases where that might actually _not_ raise an error?".  That is, I don't it's possible to create a `Signal()` with VARARGS... and there has to be an upper limit on the number of positional arguments that we'll ever actually encounter in the wild.  (50 seems safe but we could go to 1000 and I don't think it will make a performance difference)

**Comment by Czaki** [comment]
I see. This may be a nice solution, but I still would like to have max_args argument of `connect` next to such mechanism.
