### ISSUE TITLE
proposal: `CheckableSelectableEventedList`

### ISSUE THREAD

**Issue by alisterburt** [tlambert03/psygnal#74]
This might be better over at superqt, asking here because the `SelectableEventedList` will hopefully be here soon

I love the `SelectableEventedList` model and associated Qt view, I can imagine something similar with a `Checkable` mixin which provides a `CheckState` for each item in a list/tree would be really useful but can't see a clear path to it

<img width="70" alt="image" src="https://user-images.githubusercontent.com/7307488/155862064-03112d20-22c1-480a-80d7-794f75733520.png">

Would you consider something like this either here or over at superqt? If so, would you be keen to pair on it at some point?

**Comment by tlambert03** [comment]
Hmm, my about that is probably that should be an attribute on the item _in_ the list, rather than something on the selection model itself.  You can imagine that this could go forever: `CheckableSelectableHideable<InsertAttributeHereable>EventedList` :joy:

So at some point, one defers to the ItemDelegate and Qt model being used to _show_ the item, rather than the list that contains the item.  For example, in napari, the "check state" of a layer in the layer list is based on the `layer.visible` attribute.  The `QAbstractItemModel.data()` method is responsible for querying attributes from each item in the model and creating a visual editor for them. [here's where it gets pulled from the model in napari](https://github.com/tlambert03/napari/blob/842008f6df909bcbc391789badd7f2414eed6ec4/napari/_qt/containers/qt_layer_model.py#L22-L23):
```py
class QtLayerListModel(QtListModel[Layer]):
    def data(self, index: QModelIndex, role: Qt.ItemDataRole):
        """Return data stored under ``role`` for the item at ``index``."""
        layer = self.getItem(index)
        if role == Qt.CheckStateRole:  # the "checked" state of this item
            return Qt.Checked if layer.visible else Qt.Unchecked
        ...
```

**Comment by tlambert03** [comment]
I'm going to close this since i think we've got enough to work with on the pure python side now.  Most of the remaining visual elements will come on the superqt side.

**Comment by alisterburt** [comment]
`CheckableSelectableHideable<InsertAttributeHereable>EventedList` oh but that sounds so fun 😆 

You're totally right and thank you for taking the time to explain - I need more experience with the different roles in models moving forward I think :)
